### PR TITLE
Add return capability and unify Resilient Operation Builders with Unit!

### PR DESCRIPTION
**Pull request by psibernetic**
Remaining work:
- [x] Unit tests on op.Return(val)

### CODE REVIEW

**Comment by psibernetic** [comment]
@FacetiousProgrammer You are definitely going to want to see this.

**Comment by psibernetic** [comment]
@Tyrotoxin Interesting use of self-defined Unit here for you to muse over.

**Comment by psibernetic** [comment]
It is targeting net452, but I will add net46 as an explicit target as well for package sanity.

 Is that what you were asking?

**Comment by tyrotoxin** [comment]
I was asking to introduce the `unit` type to the C# language repo

**Comment by psibernetic** [comment]
Haha On It

**Pull request merged**
